### PR TITLE
Add support for multiple galleries per page

### PR DESCRIPTION
**Pull request by davidklaw**
A solution for Issue #4.
- Updated the framework to use unique ids for generated galleries
- Updated example index.html to include two galleries
- Updated readme

### CODE REVIEW

**Comment by ghost** [comment]
Thank you for the fix! It looks like the dark background overlay disappears though. Just have to add the numbers to the css:

#galleryOverlay_0, 
#galleryOverlay_1,
#galleryOverlay_2 {
...
}
#galleryOverlay_0.visible,
#galleryOverlay_1.visible,
#galleryOverlay_2.visible {
...
}

Unless there's a jQuery way to do it.. but I'm not that advanced :(

**Comment by ghost** [comment]
Looks like a better fix is to just change the #galleryOverlay to .galleryOverlay and #galleryOverlay.visible to .galleryOverlay.visible then overlay.addClass("galleryOverlay "); in touchtouch.js

**Comment by davidklaw** [comment]
Excellent catch @jameskopacz. I've added a new commit to this PR that does just that. Somehow I ended up overlooking the styling in my original change.

**Comment by funwithtriangles** [comment]
I'm not sure if this is the best implementation for multiple galleries. The convention is usually to define it in the HTML, perhaps with a "data-gallery" attribute on the tag. My branch with this implementation, not fully tested but seems okay:

https://github.com/iamalexkempton/touchTouch

**Comment by davidklaw** [comment]
@iamalexkempton Good thought @iamalexkempton. I glanced at it and like the but want to pull it down and test it out this weekend. Noticed two things:
- Media query #thumbs didn't get updated to .thumbs
- Having to specify data-gallery for every li is meh, wondering if there's an alternative?

:hamburger:

**Comment by funwithtriangles** [comment]
@davidklaw Nice spot on the missing change there, fixed. Definitely could have the option to give the data-gallery attribute to the parent list element. I think having the option of either would be optimal. I'll give it a shot at some point next week, or feel free to have a go!

**Comment by davidklaw** [comment]
Closing. See #8 for a better solution.

**Pull request closed without merging**
